"设置编码
set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8

"显示行号
set number

"突显当前行
"set cursorline

"显示括号
set showmatch

"匹配括号高亮的时间（单位是十分之一秒）
set matchtime=1

"设置Tab长度为4空格'
set tabstop=4
set expandtab
"设置自动缩进长度为4空格'
set shiftwidth=4

"继承前一行的缩进方式，适用于多行注释'
set autoindent

"右键粘贴格式不会错乱
set paste
set listchars=tab:>-,trail:-

"显示光标当前位置'
set ruler

"不要使用vi的键盘模式，而是vim自己的
set nocompatible

"语法高亮
set syntax=on

"去掉输入错误的提示声音
set noeb

"不要用空格代替制表符
"set noexpandtab"

"搜索忽略大小写
set ignorecase

"搜索逐字符高亮
set hlsearch
set incsearch

"highlight WhitespaceEOL ctermbg=red guibg=red
"match WhitespaceEOL /\s\+$/

highlight ExtraWhitespace ctermbg=red guibg=red
autocmd BufWinEnter * match ExtraWhitespace /\s\+$\| \+\ze\t\+\|\t\+\zs \+/

"error 不再发声警告"
set noeb
"代替声音为警告
"set vb

"set ctags 选项"
set tags=tags
map <c-]> g<c-]>

""代码补全
"set completeopt=preview,menu
"
""打开文件类型检测, 加了这句才可以用智能补全
"set completeopt=longest,menu

"历史命令
set history=50

"使得按退格键一次可以删除4个空格
set softtabstop=4
